language: ruby
rvm:
  - 2.1

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script:
  - bundle exec jekyll build --destination out

after_success:
 - git config --global user.name "Travis CI"
 - git config --global user.email "k.suryawanshi@gmail.com"
 - cd out
 - git init
 - git add .
 - git commit -m "Deploy to GitHub Pages"
 - git push --force --quiet "https://$GITHUB_API_KEY@github.com/kaunteya/kaunteya.github.io.git" master
